site_name: CourseProject
site_description: Course project for CS 410
site_author: Your Name

repo_url: https://github.com/andreev-io/CourseProject
edit_uri: https://github.com/andreev-io/CourseProject/edit/main/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Advanced: advanced.md
  - About:
    - Release Notes: about/changelog.md
    - Contributing: about/contributing.md
    - License: about/license.md
