version: "3.9"
   
services:
  web:
    build: .
    #command: python3 manage.py runserver 0.0.0.0:8000
    #command: python3 -m flask run --host=0.0.0.0
   #volumes:
    #  - .:/code
    ports:
      # - "8000:8000"
    - "80:80"
